[package]
name = "pubdrop"
version = "1.0.0"
authors = ["eclipseeer <eclipseeer@gmail.com>"]
edition = "2018"

[dependencies]
near-sdk = "4.0.0-pre.4"

[dev-dependencies]
near-sdk-sim = "4.0.0-pre.4"

[lib]
crate-type = ["cdylib", "rlib"]
